### PR TITLE
Add a shallow copy method to AddressList

### PR DESCRIPTION
**Pull request by b0d0nne11**

### CODE REVIEW

**Comment by b0d0nne11** [comment]
`Address` is immutable but `AddressList` is not. I needed `copy` to fix a bug in our api where we call `add`/`remove` while iterating over the `AddressList`. This way we can iterate over the copy will mutating the source list.

**Comment by horkhe** [comment]
Sorry, missed that the change is for the `AddressList`. But would not just calling `addr_list_copy = AddressList(addr_list)` work?

**Comment by b0d0nne11** [comment]
It would. That's pretty much what the `copy` method is doing. I just thought that `copy` was more clear and intuitive, especially since `AddressList` already duplicates some other list functions like `append`, `remove`, `__getitem__`, etc.

**Comment by horkhe** [comment]
IMHO the thinner interface the better. Fewer things to test and maintain.

**Comment by b0d0nne11** [comment]
Fair enough.

**Pull request closed without merging**
