### PR TITLE
Added support for generating DKIM and DomainKey message signatures.

### PR DESCRIPTION
**Pull request by alex**
We plan to add support for Relaxed canonicalization, as well as verification soonish.

### CODE REVIEW

**Comment by glyph** [comment]
Ahem.

*bump*

**Comment by ralphm** [comment]
ok to test

**Comment by ralphm** [comment]
Jenkins, ok to test; test this please.

**Comment by ralphm** [comment]
Jenkins, ok to test; test this please?

**Comment by ralphm** [comment]
Jenkins, ok to test; test this please?

**Comment by ralphm** [comment]
Jenkins, ok to test; test this please?

**Comment by glyph** [comment]
Can someone who can see those failures maybe say what they are?

**Comment by ralphm** [comment]
First off, sorry for the ticket spam. Apparently we haven't properly configured Jenkins to accept magic comment phrases. Looking into that. Also, we should probably set up TravisCI for this project.

The failure is this:
```
ERROR: Failure: AttributeError ('module' object has no attribute 'load_pem_pkcs8_private_key')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/jenkins/shiningpanda/jobs/1cc186e5/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/mg/jenkins/shiningpanda/jobs/1cc186e5/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/mg/jenkins/shiningpanda/jobs/1cc186e5/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/var/mailgun/jenkins/workspace/flanker-pr/tests/dkim_test.py", line 27, in <module>
    DUMMY_RSA_KEY = serialization.load_pem_pkcs8_private_key(b"""
AttributeError: 'module' object has no attribute 'load_pem_pkcs8_private_key'
```

I believe that function was removed long time ago, no?

**Pull request merged**
