### PR TITLE
Incrase max ops 10x

### PR DESCRIPTION
**Pull request by grinich**
In practice there are actually messages with over 500 attachments. We've seen this at [Nylas](https://nylas.com) while running our sync engine that provides an email API. 

You can simulate the failure with this script:

```
from flanker import mime
import uuid

msg = mime.create.multipart('alternative')
msg.append(
    mime.create.text('plain', 'Hello'),
    mime.create.text('html', '<html>Hello</html>'))

text_msg = msg
msg = mime.create.multipart('mixed')

msg.append(text_msg)

for a in range(5000):
    # Disposition should be inline if we add Content-ID
    msg.append(mime.create.attachment(
        'text/plain',
        str(uuid.uuid4())))


msg.headers['Subject'] = 'Breaks Flanker'
msg.headers['To'] = u'bar@example.com'
msg.headers['From'] = 'foo@example.com'

rfcmsg = msg.to_string()

break_msg = mime.from_string(rfcmsg)
```

Throws

```
Traceback (most recent call last):
  File "too_many_attachments.py", line 27, in <module>
    break_msg = mime.from_string(rfcmsg)
  File "/Users/mg/workspace/sync-engine/flanker/flanker/mime/create.py", line 82, in from_string
    return scanner.scan(string)
  File "/Users/mg/workspace/sync-engine/flanker/flanker/mime/message/scanner.py", line 24, in scan
    return traverse(Start(), TokensIterator(tokens, string))
  File "/Users/mg/workspace/sync-engine/flanker/flanker/mime/message/scanner.py", line 96, in traverse
    parts.append(traverse(token, iterator, content_type))
  File "/Users/mg/workspace/sync-engine/flanker/flanker/mime/message/scanner.py", line 34, in traverse
    iterator.check()
  File "/Users/mg/workspace/sync-engine/flanker/flanker/mime/message/scanner.py", line 270, in check
    self.opcount, _MAX_OPS))
flanker.mime.message.errors.DecodingError: Too many parts: 501, max is 500
```

Obviously one can create an email message with a nearly arbitrary number of attachments, but with our entire mail corpus, we haven't seen any that hit the limit in this commit. It's also worth noting that we have not experienced any "runaway" parsing that would require this limit check in the first place. (Perhaps it was only used when Flanker was being developed?)

### CODE REVIEW

**Comment by rmihael** [comment]
We also met this problem recently with our corpus. Is it planned to include this adjustment to a next published release?

**Comment by ralphm** [comment]
This PR fails its tests with the following:

```
FAIL: tests.mime.message.scanner_test.bad_messages_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/jenkins/shiningpanda/jobs/1cc186e5/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/mailgun/jenkins/workspace/flanker-pr/tests/mime/message/scanner_test.py", line 161, in bad_messages_test
    assert_raises(DecodingError, scan, ENCLOSED_ENDLESS)
AssertionError: DecodingError not raised
```

Given that `master` passes this test, and the branch is quite old, @grinich could you maybe rebase it?

**Comment by grinich** [comment]
Just rebased and I'm not sure why the builds are failing. The branches have literally a 1 character difference... https://github.com/mailgun/flanker/compare/master...nylas:master

**Comment by horkhe** [comment]
Hey @mhahnenberg do you still want to merge this changes to the master? Looks like you collected several assorted commits here. Some of them are not relevant anymore. So if you do then let me know and I can work with you on making this happen.

**Comment by mhahnenberg** [comment]
Huh, didn't realize this was updating every time we pushed something. We'd really like Python 3 support, but it could be nice for us to get back onto upstream flanker in the interim.

**Comment by horkhe** [comment]
@mhahnenberg I hear you. I'll see what I can do.

**Comment by mhahnenberg** [comment]
I think I successfully rebased onto upstream/master. I'll try opening another PR.

**Comment by horkhe** [comment]
@mhahnenberg I guess this one can be closed?

**Comment by mhahnenberg** [comment]
Yeah! 👍

**Pull request closed without merging**
