### PR TITLE
Make addresslib Python 3 compatible

### PR DESCRIPTION
**Pull request by horkhe**
This PR makes flanker/addresslib Python 3 compatible.

The current functionality when running in Python 2 is not changed. In Python 3 we expect text inputs (str) and all methods that return string types (str/unicode) in Python 2 are returning str unconditionally.

The only problem that I have not yet fixed is that ASCII separator symbols `0x1c, 0x1d, 0x1e, 0x1f` for some reason became allowed in the display name in Python 3.

### CODE REVIEW

**Comment by pudo** [comment]
This is amazing news. Is there a sense of when Python 3 support may be released?

**Comment by horkhe** [comment]
@pudo I am working on it. Although we at Mailgun do not use Python 3, so this is a side project for me.

@b0d0nne11 could you please take a look at the changes.

**Comment by JamesMcGuigan** [comment]
If flanker now has full python 3 compatibility, would it be possible to possible to push a new release to PyPi such that it can be easily installed via pip?

**Comment by horkhe** [comment]
@JamesMcGuigan unfortunately Flanker does not have full Python 3 compatibility yet. Only a [limited set of packages](https://github.com/mailgun/flanker/blob/master/build.sh#L11-L19) is Python 3 compatible. I have not been able to continue the work due to lack of time.

**Pull request merged**
