### PR TITLE
Increase max ops

### PR DESCRIPTION
**Pull request by mhahnenberg**
Breaking the original PR (#87) into a new one on a separate branch with a fix for the tests.

### CODE REVIEW

**Comment by horkhe** [comment]
@b0d0nne11 I am fine with that. I have never actually seen this exception in production. what do you think?

**Comment by b0d0nne11** [comment]
Same here. Sounds fine to me.

**Comment by horkhe** [comment]
@mhahnenberg please rebase, then I will merge it.

**Comment by mhahnenberg** [comment]
Thank you!

**Pull request merged**
